# Generated by Django 3.1.3 on 2020-11-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='wantpublic',
            field=models.BooleanField(default=True),
        ),
    ]
