# Generated by Django 3.1.3 on 2020-11-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20201128_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.CharField(max_length=2000),
        ),
    ]
