# Generated by Django 3.1.3 on 2020-11-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20201129_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
